---
grails:
    plugin:
        springsecurity:
            adh:
                errorPage: null
            userLookup:
              userDomainClassName: 'daweb3.User'
              authorityJoinClassName: 'daweb3.UserRole'
            authority:
              className: 'daweb3.Role'
            logoff:
              afterLogoutUrl: '/login/auth'
            rejectIfNoRule: false
            fii:
              rejectPublicInvocations: false
            useSecurityEventListener: true
            successHandler:
              defaultTargetUrl: '/'
              alwaysUseDefault: true
            useBasicAuth: true
            basic:
              realmName: "DAWEB - DNSCORE"
---
server:
  port: 8095
---
grails:
  assets:
    bundle: true
    storagePath: /home/gbender/assets
---
grails:
    profile: web
    codegen:
        defaultPackage: daweb3
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: true         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        
jms:
    containers:
        standard:
            messageConverter: null

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    activemq:
        brokerUrl: vm://localhost
        pooled: true
        

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
        extension : true
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            code  cs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh: 
                preprocess: true
    scaffolding:
       templates:
           domainSuffix: Instance     
    exceptionresolver:
       params:
            exclude: password
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: true
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: cb_usr
    password: 4qS1BWisL6gUrvNYVFgFog==

environments:
  development:
    dataSource: 
      pooled: true
      url: jdbc:postgresql://localhost:5432/CB
      dbCreate: validate
      passwordEncryptionCodec: de.uzk.hki.da.utils.DESCodec
      characterEncoding: UTF-8
    config:
      locations: ["file:${userHome}/.grails/${appName}_properties.groovy"]
    localNode:
      id: 1
      userAreaRootPath: /ci/storage/UserArea
      ingestAreaRootPath: /ci/storage/IngestArea
    transferNode:
      downloadLinkPrefix: "prefix for URL to download DIP"
    loginManager: de.uzk.hki.da.login.PlainLogin  
    cb:
      port: 4455
      presServer: "CB nodename of fedora Server"
    irods:
      server: localnode
      default_resc: ciWorkingResource
      zone: c-i
    fedora:
      urlPrefix: "http://prefix_for_fedora/fedora/objects/"
              
  test:
    dataSource: 
      pooled: true
      url: jdbc:postgresql://localhost:5432/CB
      dbCreate: validate
      passwordEncryptionCodec: de.uzk.hki.da.utils.DESCodec
      characterEncoding: UTF-8
      config:
        locations: ["file:${userHome}/.grails/${appName}_properties.groovy"] 
      localNode:
        id: 1
        userAreaRootPath: /ci/storage/UserArea
      logging:
        jul:
          userbridge: true     
      loginManager: de.uzk.hki.da.login.PlainLogin      
      cb:
        port: 4455
        presServer: "CB nodename of fedora Server"    
      irods:
        server: localnode
        default_resc: ciWorkingResource
        zone: c-i
      fedora:
        urlPrefix: "http://prefix_for_fedora/fedora/objects/"
            
    production:
      dataSource:
        dbCreate: none
        url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        properties:
          jmxEnabled: true
          initialSize: 5
          maxActive: 50
          minIdle: 5
          maxIdle: 25
          maxWait: 10000
          maxAge: 600000
          timeBetweenEvictionRunsMillis: 5000
          minEvictableIdleTimeMillis: 60000
          validationQuery: SELECT 1
          validationQueryTimeout: 3
          validationInterval: 15000
          testOnBorrow: true
          testWhileIdle: true
          testOnReturn: false
          jdbcInterceptors: ConnectionState
          defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
          config:
            locations: ["file:${userHome}/.grails/${appName}_properties.groovy"]
        logging:
        jul:
          userbridge: true        
